version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  
      - MYSQL_DATABASE=events_db  
    ports:
      - 3306:3306  
    volumes:
      - db:/var/lib/mysql  

  app-events:
    depends_on:
      - mysqldb
    image: azizbouza15/eventsproject:latest  
    # build: ./  # Uncomment if you want to build the app locally instead of using an image
    restart: on-failure
    ports:
      - 8082:8082  # Expose the application port
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/events_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "your_password_here",  # Use your actual password here
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: